### ISSUE TITLE
Reactions to messages with mentions gives an avocado to the user who posted the message

### ISSUE THREAD

**Issue by Jrc356** [Jrc356/avokudos#8]
It appears that when someone reacts to a message containing mentions, the avocado goes to the poster of the message instead of the mentioned users

**Comment by CesarLanderos** [comment]
Be aware of exceptions:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/815951/208158239-0911ea5b-a461-4710-bd6f-fe29c485be1d.png">

I guess the bot should not receive avokudos... or i don't know ¯\_(ツ)_/¯

**Comment by Jrc356** [comment]
@CesarLanderos I opened #12 and #13 to track bot users and special @'s
